# -*- coding: utf-8 -*-
# fmt: off
# flake8: noqa

MOCK_STAGES = {
    "Topic": {
        "sequence_number": None,
        "object": "message",
        "status": "created",
        "error": None,
        "id": "msg_03829246-1795-49e5-9ad7-874119b48df8",
        "type": "Topic",
        "role": "user",
        "content": [
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": None,
                "delta": False,
                "msg_id": None,
                "text": "百炼椰汁",
            },
        ],
        "code": None,
        "message": None,
        "usage": None,
    },
    "Script": {
        "sequence_number": None,
        "object": "message",
        "status": "created",
        "error": None,
        "id": "msg_d1619831-5dd8-4855-94e2-724e7eb0d81c",
        "type": "message",
        "role": None,
        "content": [
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "data",
                "index": None,
                "delta": False,
                "msg_id": None,
                "data": {
                    "product_name": "百炼椰汁",
                    "product_desc": "百炼椰汁采用优质椰子榨取而成，瓶身简洁大方，透明包装展示出清澈的椰汁色泽。每一口都充满浓郁的椰香，口感顺滑，清甜可口，适合各种烹饪和饮品搭配。",
                    "slogan": "百变美味，源自纯粹椰香！",
                    "image_url": "https://dashscope-result-wlcb-acdr-1.oss-cn-wulanchabu-acdr-1.aliyuncs.com/1d/33/20250921/2cf8887b/afc7ea0e-e9b5-40d0-9a5b-17e7632fa0fc2356394244.png?Expires=1758516578&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=0VR32akSimhGbaa%2F9yE9%2FcgNqZU%3D",
                    "script": "《椰汁的百变魔法》\n\n炎热的夏日午后，小宝和妈妈在厨房里忙碌着。小宝看着满桌的食材，皱起了眉头：“妈妈，今天又要做什么呀？”\n\n妈妈神秘一笑，从冰箱里拿出一瓶冰凉的百炼椰汁：“今天我们要做一款特别的夏日甜品——椰汁芒果冰沙！”\n\n小宝的眼睛亮了起来：“真的吗？我最喜欢椰汁了！” 妈妈打开百炼椰汁，浓郁的椰香立刻弥漫开来。“先来一杯纯正的椰汁解解渴吧！” 小宝迫不及待地接过杯子，喝了一口，赞叹道：“哇，好香好甜！”\n\n接着，妈妈把椰汁倒入搅拌机，加入新鲜芒果和冰块，按下开关。不一会儿，一杯金黄诱人的椰汁芒果冰沙就做好了。“看，这就是我们的夏日魔法！” 小宝尝了一口，惊喜地说：“太好喝了！”\n\n这时，爸爸走进厨房，看到桌上摆着的椰汁芒果冰沙，也忍不住尝了一口：“嗯，这椰汁真不错，清新又解渴！”\n\n妈妈笑着对小宝说：“有了百炼椰汁，我们每天都能做出不一样的美味，让这个夏天不再单调！”\n\n角色： 妈妈，善于用简单食材制作美味的家庭主妇。\n角色： 小宝，一个好奇心强、喜欢尝试新事物的小男孩。\n角色： 爸爸，被美味吸引进厨房的“吃货”。\n产品名称：百炼椰汁\n产品描述：百炼椰汁采用优质椰子榨取而成，瓶身简洁大方，透明包装展示出清澈的椰汁色泽。每一口都充满浓郁的椰香，口感顺滑，清甜可口，适合各种烹饪和饮品搭配。\n产品标语：百变美味，源自纯粹椰香！",
                },
            },
        ],
        "code": None,
        "message": None,
        "usage": None,
    },
    "Storyboard": {
        "sequence_number": None,
        "object": "message",
        "status": "created",
        "error": None,
        "id": "msg_7b6bb18b-ab02-44c8-af36-b7c8050b9a66",
        "type": "message",
        "role": "assistant",
        "content": [
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 0,
                "delta": False,
                "msg_id": None,
                "text": "角色：妈妈, 小宝\n画面：厨房里，小宝看着满桌的食材皱眉，妈妈神秘地从冰箱拿出一瓶冰凉的百炼椰汁。\n旁白：炎热午后，一份清凉惊喜即将诞生。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 1,
                "delta": False,
                "msg_id": None,
                "text": "角色：妈妈, 小宝\n画面：妈妈打开百炼椰汁，浓郁椰香弥漫开来，小宝接过杯子喝了一口，露出满意的笑容。\n旁白：纯正椰香，清甜解渴。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 2,
                "delta": False,
                "msg_id": None,
                "text": "角色：妈妈, 小宝, 爸爸\n画面：妈妈将椰汁倒入搅拌机，加入芒果和冰块，制作出金黄诱人的椰汁芒果冰沙。爸爸走进厨房尝了一口，赞不绝口。\n旁白：夏日魔法，美味无限。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 3,
                "delta": False,
                "msg_id": None,
                "text": "角色：妈妈, 小宝, 爸爸\n画面：一家三口围坐在餐桌旁，享受着椰汁芒果冰沙，脸上洋溢着幸福的笑容。\n旁白：百变美味，让夏天不再单调。",
            },
        ],
        "code": None,
        "message": None,
        "usage": None,
    },
    "RoleDescription": {
        "sequence_number": None,
        "object": "message",
        "status": "created",
        "error": None,
        "id": "msg_e810e42c-aa69-467d-a1ea-c93599319423",
        "type": "message",
        "role": "assistant",
        "content": [
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 0,
                "delta": False,
                "msg_id": None,
                "text": "角色：妈妈\n角色描述：气质温柔，面带微笑，长发束成马尾。服饰：浅蓝色围裙与白色T恤（明亮的厨房）。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 1,
                "delta": False,
                "msg_id": None,
                "text": "角色：小宝\n角色描述：好奇心强，活泼可爱，圆脸大眼睛，短发。服饰：黄色T恤与牛仔短裤（明亮的厨房）。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 2,
                "delta": False,
                "msg_id": None,
                "text": "角色：爸爸\n角色描述：温和亲切，微笑着，短发干净利落。服饰：灰色T恤与休闲长裤（明亮的厨房）。",
            },
        ],
        "code": None,
        "message": None,
        "usage": None,
    },
    "RoleImage": {
        "sequence_number": None,
        "object": "message",
        "status": "created",
        "error": None,
        "id": "msg_e0e59735-6e3a-4638-a420-706f6bb4a843",
        "type": "message",
        "role": "assistant",
        "content": [
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "data",
                "index": None,
                "delta": False,
                "msg_id": None,
                "data": {
                    "妈妈": "https://dashscope-result-wlcb-acdr-1.oss-cn-wulanchabu-acdr-1.aliyuncs.com/1d/d3/20250921/2cf8887b/f0f923bc-7084-4eb1-a519-aeb01ea82b851332923321.png?Expires=1758516639&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=dpJ3m%2B34hgEE5g1XJDXbinc9ot0%3D",
                    "小宝": "https://dashscope-result-wlcb-acdr-1.oss-cn-wulanchabu-acdr-1.aliyuncs.com/1d/8f/20250921/2cf8887b/6dd32642-0f69-40d4-bf9f-40531dd5a02a2188097946.png?Expires=1758516621&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=F1A%2FMHLfYSszQC5krVDZBWF3ZZk%3D",
                    "爸爸": "https://dashscope-result-wlcb-acdr-1.oss-cn-wulanchabu-acdr-1.aliyuncs.com/1d/d2/20250921/2cf8887b/d0aeb16a-2f0b-4225-bf83-6a32d5e07cda2465314635.png?Expires=1758516660&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=HSlASgnLa0saO2s97ohynltTXUg%3D",
                },
            },
        ],
        "code": None,
        "message": None,
        "usage": None,
    },
    "FirstFrameDescription": {
        "sequence_number": None,
        "object": "message",
        "status": "created",
        "error": None,
        "id": "msg_02fff2d4-6d4c-4914-b673-e3145fd0e24d",
        "type": "message",
        "role": "assistant",
        "content": [
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 0,
                "delta": False,
                "msg_id": None,
                "text": "角色：妈妈, 小宝\n首帧描述：现代简约风格，在明亮的厨房里，小宝穿着黄色T恤与牛仔短裤，皱着眉头看着满桌的食材。妈妈穿着浅蓝色围裙与白色T恤，长发束成马尾，神秘地从冰箱中拿出一瓶冰凉的百炼椰汁，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 1,
                "delta": False,
                "msg_id": None,
                "text": "角色：妈妈, 小宝\n首帧描述：现代简约风格，在明亮的厨房里，妈妈打开百炼椰汁，浓郁的椰香弥漫开来。小宝穿着黄色T恤与牛仔短裤，接过杯子喝了一口，露出满意的笑容，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 2,
                "delta": False,
                "msg_id": None,
                "text": "角色：妈妈, 小宝, 爸爸\n首帧描述：现代简约风格，在明亮的厨房里，妈妈将百炼椰汁倒入搅拌机，加入新鲜芒果和冰块，制作出金黄诱人的椰汁芒果冰沙。爸爸穿着灰色T恤与休闲长裤走进厨房，尝了一口，赞不绝口，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 3,
                "delta": False,
                "msg_id": None,
                "text": "角色：妈妈, 小宝, 爸爸\n首帧描述：现代简约风格，在明亮的厨房里，一家三口围坐在餐桌旁，享受着椰汁芒果冰沙，脸上洋溢着幸福的笑容。妈妈穿着浅蓝色围裙与白色T恤，小宝穿着黄色T恤与牛仔短裤，爸爸穿着灰色T恤与休闲长裤，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
        ],
        "code": None,
        "message": None,
        "usage": None,
    },
    "FirstFrameImage": {
        "sequence_number": None,
        "object": "message",
        "status": "created",
        "error": None,
        "id": "msg_2dc291d0-2394-4173-89f9-63a042119f8f",
        "type": "message",
        "role": "assistant",
        "content": [
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": None,
                "delta": False,
                "msg_id": None,
                "text": "角色：妈妈, 小宝\n首帧描述：现代简约风格，在明亮的厨房里，小宝穿着黄色T恤与牛仔短裤，皱着眉头看着满桌的食材。妈妈穿着浅蓝色围裙与白色T恤，长发束成马尾，神秘地从冰箱中拿出一瓶冰凉的百炼椰汁，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "image",
                "index": None,
                "delta": False,
                "msg_id": None,
                "image_url": "https://dashscope-result-wlcb-acdr-1.oss-cn-wulanchabu-acdr-1.aliyuncs.com/1d/1b/20250921/2cf8887b/1bf43116-2043-488a-8861-f9fd863b6ee72265152426.png?Expires=1758516710&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=2K7D4Ff297%2FE4CzR%2BuIop5uFa4o%3D",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": None,
                "delta": False,
                "msg_id": None,
                "text": "角色：妈妈, 小宝\n首帧描述：现代简约风格，在明亮的厨房里，妈妈打开百炼椰汁，浓郁的椰香弥漫开来。小宝穿着黄色T恤与牛仔短裤，接过杯子喝了一口，露出满意的笑容，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "image",
                "index": None,
                "delta": False,
                "msg_id": None,
                "image_url": "https://dashscope-result-wlcb-acdr-1.oss-cn-wulanchabu-acdr-1.aliyuncs.com/1d/8e/20250921/2cf8887b/ce12af2b-f0ee-403e-aaad-1d2cc7cd2ed73146178173.png?Expires=1758516710&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=yKMAxD2esuJ2391lTlNlazsN0V0%3D",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": None,
                "delta": False,
                "msg_id": None,
                "text": "角色：妈妈, 小宝, 爸爸\n首帧描述：现代简约风格，在明亮的厨房里，妈妈将百炼椰汁倒入搅拌机，加入新鲜芒果和冰块，制作出金黄诱人的椰汁芒果冰沙。爸爸穿着灰色T恤与休闲长裤走进厨房，尝了一口，赞不绝口，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "image",
                "index": None,
                "delta": False,
                "msg_id": None,
                "image_url": "https://dashscope-result-wlcb-acdr-1.oss-cn-wulanchabu-acdr-1.aliyuncs.com/1d/8b/20250921/2cf8887b/f5c4970e-4914-4611-b8e8-d7debe3c5bb51669662344.png?Expires=1758516732&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=eW0z3p9QlBhCQwwdANK0KmGp9LY%3D",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": None,
                "delta": False,
                "msg_id": None,
                "text": "角色：妈妈, 小宝, 爸爸\n首帧描述：现代简约风格，在明亮的厨房里，一家三口围坐在餐桌旁，享受着椰汁芒果冰沙，脸上洋溢着幸福的笑容。妈妈穿着浅蓝色围裙与白色T恤，小宝穿着黄色T恤与牛仔短裤，爸爸穿着灰色T恤与休闲长裤，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "image",
                "index": None,
                "delta": False,
                "msg_id": None,
                "image_url": "https://dashscope-result-wlcb-acdr-1.oss-cn-wulanchabu-acdr-1.aliyuncs.com/1d/63/20250921/2cf8887b/6c6a36fb-bdde-4939-9280-023569e5e13a1378840166.png?Expires=1758516733&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=WqD3IPdouJI7CiGSwFZ%2Bn8oXYLY%3D",
            },
        ],
        "code": None,
        "message": None,
        "usage": None,
    },
    "VideoDescription": {
        "sequence_number": None,
        "object": "message",
        "status": "created",
        "error": None,
        "id": "msg_1e4421c2-9bde-47f1-b06e-be0e2d21d5cd",
        "type": "message",
        "role": "assistant",
        "content": [
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 0,
                "delta": False,
                "msg_id": None,
                "text": "描述：中景，明亮的厨房里，小宝穿着黄色T恤与牛仔短裤，皱着眉头看着满桌的食材。妈妈穿着浅蓝色围裙与白色T恤，长发束成马尾，神秘地从冰箱中拿出一瓶冰凉的百炼椰汁，瓶身透明展示出清澈的椰汁色泽，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 1,
                "delta": False,
                "msg_id": None,
                "text": "描述：特写，妈妈打开百炼椰汁，浓郁的椰香立刻弥漫开来。接着，镜头切换到小宝接过杯子喝了一口，露出满意的笑容，表情生动自然，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 2,
                "delta": False,
                "msg_id": None,
                "text": "描述：中景，妈妈将百炼椰汁倒入搅拌机，加入新鲜芒果和冰块，按下开关。镜头切换到搅拌机内部，看到椰汁、芒果和冰块混合搅拌的过程，画面流畅动感。随后，爸爸穿着灰色T恤与休闲长裤走进厨房，尝了一口刚做好的金黄诱人的椰汁芒果冰沙，赞不绝口，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 3,
                "delta": False,
                "msg_id": None,
                "text": "描述：远景，一家三口围坐在餐桌旁，享受着椰汁芒果冰沙，脸上洋溢着幸福的笑容。妈妈穿着浅蓝色围裙与白色T恤，小宝穿着黄色T恤与牛仔短裤，爸爸穿着灰色T恤与休闲长裤，场景温馨和谐，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
        ],
        "code": None,
        "message": None,
        "usage": None,
    },
    "Video": {
        "sequence_number": None,
        "object": "message",
        "status": "created",
        "error": None,
        "id": "msg_61fff176-756b-4b15-a4aa-67bda484f2bd",
        "type": "message",
        "role": "assistant",
        "content": [
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": None,
                "delta": False,
                "msg_id": None,
                "text": "描述：中景，明亮的厨房里，小宝穿着黄色T恤与牛仔短裤，皱着眉头看着满桌的食材。妈妈穿着浅蓝色围裙与白色T恤，长发束成马尾，神秘地从冰箱中拿出一瓶冰凉的百炼椰汁，瓶身透明展示出清澈的椰汁色泽，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "data",
                "index": None,
                "delta": False,
                "msg_id": None,
                "data": {
                    "https://dashscope-result-sh.oss-cn-shanghai.aliyuncs.com/1d/09/20250921/ecf8c691/63582ad4-e9fb-4e9a-8b02-4d07420e8508.mp4?Expires=1758528574&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=WVQYDyLpwKR6CHkOfrjTwNNZO0s%3D": "描述：中景，明亮的厨房里，小宝穿着黄色T恤与牛仔短裤，皱着眉头看着满桌的食材。妈妈穿着浅蓝色围裙与白色T恤，长发束成马尾，神秘地从冰箱中拿出一瓶冰凉的百炼椰汁，瓶身透明展示出清澈的椰汁色泽，色彩鲜艳，商业摄影质感，4K高清画质。",
                },
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": None,
                "delta": False,
                "msg_id": None,
                "text": "描述：特写，妈妈打开百炼椰汁，浓郁的椰香立刻弥漫开来。接着，镜头切换到小宝接过杯子喝了一口，露出满意的笑容，表情生动自然，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "data",
                "index": None,
                "delta": False,
                "msg_id": None,
                "data": {
                    "https://dashscope-result-sh.oss-cn-shanghai.aliyuncs.com/1d/63/20250921/ecf8c691/a7a26645-3970-4a76-a635-7b4e5d0fbdca.mp4?Expires=1758528570&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=BrLuORhwZGyJrk2E9YRmLJku%2FUg%3D": "描述：特写，妈妈打开百炼椰汁，浓郁的椰香立刻弥漫开来。接着，镜头切换到小宝接过杯子喝了一口，露出满意的笑容，表情生动自然，色彩鲜艳，商业摄影质感，4K高清画质。",
                },
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": None,
                "delta": False,
                "msg_id": None,
                "text": "描述：中景，妈妈将百炼椰汁倒入搅拌机，加入新鲜芒果和冰块，按下开关。镜头切换到搅拌机内部，看到椰汁、芒果和冰块混合搅拌的过程，画面流畅动感。随后，爸爸穿着灰色T恤与休闲长裤走进厨房，尝了一口刚做好的金黄诱人的椰汁芒果冰沙，赞不绝口，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "data",
                "index": None,
                "delta": False,
                "msg_id": None,
                "data": {
                    "https://dashscope-result-bj.oss-cn-beijing.aliyuncs.com/1d/62/20250921/5e291de3/813cacc9-f5f1-49f4-9f8e-00f08f3f0345.mp4?Expires=1758528640&OSSAccessKeyId=LTAI5tDUB1cEqFCYhEwWry26&Signature=exjTJosa3WYgiLLArfRc4y7Z0Sw%3D": "描述：中景，妈妈将百炼椰汁倒入搅拌机，加入新鲜芒果和冰块，按下开关。镜头切换到搅拌机内部，看到椰汁、芒果和冰块混合搅拌的过程，画面流畅动感。随后，爸爸穿着灰色T恤与休闲长裤走进厨房，尝了一口刚做好的金黄诱人的椰汁芒果冰沙，赞不绝口，色彩鲜艳，商业摄影质感，4K高清画质。",
                },
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": None,
                "delta": False,
                "msg_id": None,
                "text": "描述：远景，一家三口围坐在餐桌旁，享受着椰汁芒果冰沙，脸上洋溢着幸福的笑容。妈妈穿着浅蓝色围裙与白色T恤，小宝穿着黄色T恤与牛仔短裤，爸爸穿着灰色T恤与休闲长裤，场景温馨和谐，色彩鲜艳，商业摄影质感，4K高清画质。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "data",
                "index": None,
                "delta": False,
                "msg_id": None,
                "data": {
                    "https://dashscope-result-bj.oss-cn-beijing.aliyuncs.com/1d/96/20250921/5e291de3/ad91bcd0-08a4-4752-b982-dcb7e26da1b0.mp4?Expires=1758528637&OSSAccessKeyId=LTAI5tDUB1cEqFCYhEwWry26&Signature=eVfecfatxa5lSa45K4LMOrPYllc%3D": "描述：远景，一家三口围坐在餐桌旁，享受着椰汁芒果冰沙，脸上洋溢着幸福的笑容。妈妈穿着浅蓝色围裙与白色T恤，小宝穿着黄色T恤与牛仔短裤，爸爸穿着灰色T恤与休闲长裤，场景温馨和谐，色彩鲜艳，商业摄影质感，4K高清画质。",
                },
            },
        ],
        "code": None,
        "message": None,
        "usage": None,
    },
    "Line": {
        "sequence_number": None,
        "object": "message",
        "status": "created",
        "error": None,
        "id": "msg_0d3f07a4-f5a7-45e8-bb1e-abb47acb742a",
        "type": "message",
        "role": "assistant",
        "content": [
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 0,
                "delta": False,
                "msg_id": None,
                "text": "妈妈, 小宝",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 1,
                "delta": False,
                "msg_id": None,
                "text": "炎热午后，一份清凉惊喜即将诞生。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 2,
                "delta": False,
                "msg_id": None,
                "text": "Chelsie",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 3,
                "delta": False,
                "msg_id": None,
                "text": "妈妈, 小宝",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 4,
                "delta": False,
                "msg_id": None,
                "text": "纯正椰香，清甜解渴。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 5,
                "delta": False,
                "msg_id": None,
                "text": "Chelsie",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 6,
                "delta": False,
                "msg_id": None,
                "text": "妈妈, 小宝, 爸爸",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 7,
                "delta": False,
                "msg_id": None,
                "text": "夏日魔法，美味无限。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 8,
                "delta": False,
                "msg_id": None,
                "text": "Chelsie",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 9,
                "delta": False,
                "msg_id": None,
                "text": "妈妈, 小宝, 爸爸",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 10,
                "delta": False,
                "msg_id": None,
                "text": "百变美味，让夏天不再单调。",
            },
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "text",
                "index": 11,
                "delta": False,
                "msg_id": None,
                "text": "Chelsie",
            },
        ],
        "code": None,
        "message": None,
        "usage": None,
    },
    "Audio": {
        "sequence_number": None,
        "object": "message",
        "status": "created",
        "error": None,
        "id": "msg_254dff67-521a-4625-8e19-3923a8911b06",
        "type": "message",
        "role": "assistant",
        "content": [
            {
                "sequence_number": None,
                "object": "content",
                "status": None,
                "error": None,
                "type": "data",
                "index": None,
                "delta": False,
                "msg_id": None,
                "data": {
                    "http://dashscope-result-wlcb.oss-cn-wulanchabu.aliyuncs.com/1d/f1/20250921/e6c1b9cc/ab3b5e16-f6d5-4b2e-9151-3806ebadbb5d.wav?Expires=1758528813&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=pMhyVTDAZiDkm5Ma9IpvTCfEmpI%3D": "炎热午后，一份清凉惊喜即将诞生。",
                    "http://dashscope-result-wlcb.oss-cn-wulanchabu.aliyuncs.com/1d/0d/20250921/e6c1b9cc/366d3d9f-19fa-44e6-9268-1ac23b37358e.wav?Expires=1758528813&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=7HftD2DoV4TDLrPmTJ56K91Ggbo%3D": "纯正椰香，清甜解渴。",
                    "http://dashscope-result-wlcb.oss-cn-wulanchabu.aliyuncs.com/1d/5d/20250921/e6c1b9cc/2ae0ec06-96b2-438e-9453-de2180a8e021.wav?Expires=1758528812&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=XFsWOrdIqaELrYVVYActnPV7BYo%3D": "夏日魔法，美味无限。",
                    "http://dashscope-result-wlcb.oss-cn-wulanchabu.aliyuncs.com/1d/10/20250921/e6c1b9cc/cb2f1c6c-8d1c-47d5-99af-21daa42ca475.wav?Expires=1758528813&OSSAccessKeyId=LTAI5tKPD3TMqf2Lna1fASuh&Signature=zBcOFtP02y7lAUr43dZ557p6vLA%3D": "百变美味，让夏天不再单调。",
                },
            },
        ],
        "code": None,
        "message": None,
        "usage": None,
    },
    "Film": {
        "sequence_number": None,
        "object": "message",
        "status": "completed",
        "error": None,
        "id": "msg_f79e2d96-563c-4c34-9953-5b2e5bd26a8a",
        "type": "message",
        "role": "assistant",
        "content": [
            {
                "sequence_number": None,
                "object": "content",
                "status": "completed",
                "error": None,
                "type": "data",
                "index": 0,
                "delta": False,
                "msg_id": "msg_f79e2d96-563c-4c34-9953-5b2e5bd26a8a",
                "data": {
                    "video_url": "https://bailian-cn-beijing.oss-cn-beijing.aliyuncs.com/multimodal_generation%2Fmock_session_id%2Ffilm.mp4?OSSAccessKeyId=LTAI5tSr8GHZekwmKPw28SMf&Expires=1758447969&Signature=AjY7iDDAM59%2FM%2Fwo70%2BM3zkDxU8%3D",
                },
            },
        ],
        "code": None,
        "message": None,
        "usage": None,
    },
}

# fmt: on
